spring.application.name=ProjectHive
#this file is used to connect to a database.

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/ProjectHive
spring.datasource.username=root
spring.datasource.password=payas@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver